services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString__DefaultConnection=Server=localhost\\SQLEXPRESS;Database=ProyectoBase;Trusted_Connection=True;TrustServerCertificate=True;